#!mainFile "../main.opy"

#Subroutine names

subroutine create_status_text 5
subroutine race_change_tp 6
subroutine update_color_xp_bar 8
subroutine update_emrld_economic_parameters 9
subroutine disable_altar_effects 10
subroutine enable_display_tier_2_effects 11
subroutine init_common_player_fields 12
subroutine tier_up_reset 14  # stub: запланирован для сброса при переходе на тир выше; def появится позже
