#!mainFile "../main.opy"

#Subroutine names

subroutine chance 1  #TODO: определение (def chance) не найдено в кодовой базе
subroutine create_status_text 5
subroutine race_change_tp 6
subroutine update_color_xp_bar 8
subroutine update_emrld_economic_parameters 9
subroutine disable_altar_effects 10
subroutine enable_display_tier_2_effects 11
subroutine create_reader_holy_circle 12
subroutine destroy_reader_holy_circle 13
subroutine tier_up_reset 14
subroutine append_to_del_effects_array 15
